version: '3'

networks:
  webnet:
      driver: bridge

services:
  web:
    # command: bash -c "sequelize db:migrate && sequelize db:migrate"
    build: './'
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - webnet
    environment: 
      - DATABASE_HOST=172.18.0.1
  
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    expose:
      - '3306'
    networks:
      - webnet
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testing_db